/**
 * Known tooling locations (directories at repo root unless `path` says otherwise).
 * `sync`: overwritten in part or full by scripts/ai-sync.js when you run bun run sync.
 * `skills`: typical Agent Skills CLI (npx/bunx skills) install targets under the repo.
 */
export const ENTRIES = [
    {
        path: ".cursor",
        label: "Cursor",
        kind: "mixed",
        note: "Mixed: AI-CONFIG-INDEX.md is synced; .cursor/rules and .cursor/prompts are manual. Do not remove the whole folder unless you mean to.",
        allowDelete: false,
    },
    {
        path: ".vscode",
        label: "VS Code",
        kind: "sync",
        note: "settings.json generated by sync (editor workspace).",
        allowDelete: false,
    },
    {
        path: ".tabnine",
        label: "Tabnine",
        kind: "sync",
        note: "settings.json is regenerated by bun run sync unless `tabnine` is listed in ai-sync.exclude.json (or use --remove --yes --sync-exclude).",
        allowDelete: true,
    },
    {
        path: ".codewhisperer",
        label: "Amazon CodeWhisperer",
        kind: "sync",
        note: "settings.json is regenerated by bun run sync unless `codewhisperer` is listed in ai-sync.exclude.json (or use --remove --yes --sync-exclude).",
        allowDelete: true,
    },
    {
        path: ".github",
        label: "GitHub (incl. Copilot instructions)",
        kind: "mixed",
        note: "copilot-instructions.md is synced; workflows are not.",
        allowDelete: false,
    },
    {
        path: ".agents",
        label: "Agent Skills (.agents/skills)",
        kind: "skills",
        note: "Local skill installs; .agents/skills is gitignored.",
        allowDelete: true,
    },
    {
        path: ".skills",
        label: "Skills CLI cache (project)",
        kind: "skills",
        note: "Often gitignored; created by the skills CLI.",
        allowDelete: true,
    },
    {
        path: ".giga",
        label: "Giga",
        kind: "local",
        note: "Not generated by this repo's sync script. Safe to delete if you do not use Giga here.",
        allowDelete: true,
    },
    {
        path: ".vibe",
        label: "Mistral Vibe (skills)",
        kind: "skills",
        note: "Skills CLI target; safe to delete if unused.",
        allowDelete: true,
    },
    {
        path: ".trae",
        label: "Trae (skills)",
        kind: "skills",
        note: "Skills CLI target; safe to delete if unused.",
        allowDelete: true,
    },
    {
        path: ".windsurf",
        label: "Windsurf (rules/skills)",
        kind: "skills",
        note: "May contain skills or rules; .windsurfrules at repo root is separate (synced file).",
        allowDelete: true,
    },
    {
        path: ".claude",
        label: "Claude Code (skills)",
        kind: "skills",
        note: "Skills CLI target; CLAUDE.md at repo root is separate (synced).",
        allowDelete: true,
    },
    {
        path: ".specstory",
        label: "SpecStory",
        kind: "local",
        note: "Gitignored local tooling; safe to delete if unused.",
        allowDelete: true,
    },
    {
        path: ".frontmatter",
        label: "Front Matter (VS Code extension)",
        kind: "vscode-ext",
        note: "Extension data; deleting may reset extension state for this workspace.",
        allowDelete: true,
    },
    {
        path: ".notes",
        label: "Local notes",
        kind: "local",
        note: "Optional personal notes; not generated by sync.",
        allowDelete: true,
    },
];

export const SYNC_FILES = [
    { path: ".cursorrules", label: "Cursor rules file (root)" },
    { path: "CLAUDE.md", label: "Claude instructions (root)" },
    { path: ".windsurfrules", label: "Windsurf rules (root)" },
    { path: ".editorconfig", label: "EditorConfig (root)" },
];
